name: sparkbeta
favicon: null
layout_spectrum: 0.9339549564756453
typography_spectrum: 0.030220561660826206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9865688420832157
  lightness: 0.6311453748494387
  saturation: 0.618041726294905
  rhythmicContrast: 0.19563620910048485
purpose: []
