typography_spectrum: 0.40301
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.11459
analytics:
  google: null
  facebook: null
  twitter: null
name: spark research
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: BRAND
    id: 604e0fff-9f6a-421b-a850-f39aa6131d08
    type: content
favicon: null
title: 'join the dots, create a spark'
purpose: []
